### ISSUE TITLE
Revert SHA-1 to stable

### ISSUE THREAD

**Issue by acagliano** [acagliano/hashlib-ce#1]
Revert SHA-1 code to the slower but stable version, so I can push a VAPOR release out with stable SHA-1.
However, leave the *new* function names in the .lib and .h files.

(what we should have done at the beginning was create branches for assemblifying the code and then merge each branch in as it is written and debugged)

**Comment by beckadamtheinventor** [comment]
Done. SHA256 should also work if un-commented.
